### ISSUE TITLE
Julia + HiRedis > 769K cps

### ISSUE THREAD

**Issue by merl-dev** [stefanwille/redis-client-benchmarks#9]
Thought it would be fun to see what this is all about, so I ran a comparison on an EC2 c4.large instance.  
julia> using HiRedis

julia> start_session()
Ptr{HiRedis.RedisContext} @0x0000000003569730

julia> HiRedis.flushall()
Nullable{AbstractString}()

julia> @benchmark [kvset("foo", "bar", pipeline=true) for i=1:1000000]
BenchmarkTools.Trial:
  samples:          4
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%
  memory estimate:  190.73 mb
  allocs estimate:  4000002
  minimum time:     1.30 s (2.87% GC)
  median time:      1.30 s (2.76% GC)
  mean time:        1.30 s (2.74% GC)
  maximum time:     1.30 s (2.56% GC)

so at 1.3 secs, that implies 1,000,000 / 1.3 ~ 769,230 cps.

HiRedis is based on 'libhiredis', so there must be something very wrong with your C implementation.
Any comment?

**Comment by merl-dev** [comment]
Some more interesting aspects of your tests.  First of all, my test is actually == to your crystal test since you don't seem to check for the replies with crystal, whereas you do with libhiredis:

Crystal test:

```
N = 1_000_000

redis = Redis.new
redis.pipelined do |pipeline|
  N.times do |i|
    pipeline.set("foo", "bar")
  end
end
```

libhiredis test:

```
for(int i = 0; i < N; i++) {
      redisAppendCommand(redis,"SET foo bar");
    }

    for(int i = 0; i < N; i++) {
      redisReply *reply;
      redisGetReply(redis, (void**) &reply); // reply for SET
      freeReplyObject(reply);
    }
```

If I also run the get_reply in Julia+HiRedis:

```
function test()
       [kvset("foo", "bar", pipeline=true) for i=1:1000000]
       replies = get_reply();
 end
```

test (generic function with 1 method)

julia> `@benchmark test()`
BenchmarkTools.Trial:
  samples:          3
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%
  memory estimate:  245.50 mb
  allocs estimate:  5999000
  minimum time:     2.42 s (4.31% GC)
  median time:      2.51 s (8.10% GC)
  mean time:        2.48 s (6.85% GC)
  maximum time:     2.52 s (8.06% GC)

So I ~ half the performance, but still impressive.  What if you were to check replies in Crystal?

**Comment by stefanwille** [comment]
I do check the replies in crystal-redis, therefore also in the Crystal benchmark: 

https://github.com/stefanwille/crystal-redis/blob/master/src/redis/strategy/pipeline.cr#L25

Closing this because it's based on a false assumption.
